services:
  app:
    image: ghcr.io/elksandro2/sass-salao:latest
    container_name: sass-salao-app
    restart: always
    env_file:
      - .env
    networks:
      - proxy_network
      - db_network

networks:
  proxy_network:
    external: true
  db_network:
    external: true
